name: innoextract CI

on:
  push:
    # Runs on every pushed commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev liblzma-dev
      - name: Build innoextract
        run: |
          mkdir -p build 
          cd build
          cmake ..
          make
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: innoextract
          path: build/innoextract
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/innoextract
